# .github/workflows/fetch_arxiv.yml
name: Fetch Daily arXiv Papers

permissions:
  contents: write
  
on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜 (UTC) 运行
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install arxiv

    - name: Run Python script
      run: |
        # python arxiv_daily_fetcher.py >> content/basics/first_content.md
        echo aaa >> content/basics/first_content.md

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "0.123.8"
        extended: true

    # - name: git_pull
    #   run: |
    #     git pull

    - name: Build
      run: hugo --minify --cleanDestinationDir

    # - name: Add and commit changes
    #   run: |
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "Github Action"
    #     git add content/basics/first_content.md
    #     git add public/*
    #     git commit -m "Update arXiv papers list"

    # - name: Push changes
    #   id: git_push
    #   run: |
    #     # Pull first
    #     # git pull # --rebase origin "${GITHUB_REF}"
    #     # Push after
    #     git push origin "${GITHUB_REF}"
    #     ls /home/runner/work/github-base/
    #     echo lalala
    #     ls /home/runner/work/github-base/github-base
    #     echo 'current dir:' $PWD ${GITHUB_REF}
    #     echo 'info------------'
    #     ls /home/runner/work/github-base/github-base/public

    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: public
    #     allow_empty_commit: true

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: './public'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
